### ISSUE TITLE
how to install this plugin from source

### ISSUE THREAD

**Issue by ZENOTME** [adjacentlink/letce2-plugin-lxc#2]
Seems there is no doc for how to install this plugin form source.

**Comment by ZENOTME** [comment]
I can use following command to install it
```
autoreconf -i
./configure
make
sudo make install 
```

But when I run the letce2-tutorial, I got the error 
```
❯ make
letce2 \
	lxc \
	build \
	../node.cfg.d/ieee80211abg.cfg \
	experiment.cfg
Traceback (most recent call last):
  File "/usr/bin/letce2", line 150, in <module>
    plugins[args['subcommand']].process(nodes_include,
  File "/usr/lib/python3/dist-packages/letce2/plugins/lxc/plugin.py", line 142, in process
    self._do_build(args)
  File "/usr/lib/python3/dist-packages/letce2/plugins/lxc/plugin.py", line 159, in _do_build
    nodes = build_configuration(args['experiment-config'],
  File "/usr/lib/python3/dist-packages/letce2/engine/build.py", line 332, in build_configuration
    ofd.write(mako_template.render(**kwargs))
  File "/usr/lib/python3/dist-packages/mako/template.py", line 476, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 878, in _render
    _render_context(
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 920, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/lib/python3/dist-packages/mako/runtime.py", line 947, in _exec_template
    callable_(context, *args, **kwargs)
  File "_usr_lib_python3_dist_packages_letce2_plugins_lxc_templates_lxc_conf", line 40, in render_body
ValueError: invalid literal for int() with base 10: b'0~git2209-g5a7b9ce67\n'
make: *** [Makefile:4: all] Error 1
```

**Comment by sgalgano** [comment]
Are you using the latest version? The mako template error seems to indicate you are not. The [lxc.conf](https://github.com/adjacentlink/letce2-plugin-lxc/commit/4d0774d8ac77fecaceba63c196302278a6c66703) template changed in 0.2.9 to address the issue you are seeing.

We install all our software using the system package manager. For rpm based systems: `make rpm` for deb based systems: `make deb`.

You can find more information about installing prebuilt packages or running from local source builds in the [emane-guide](https://emane.io/getting-started).
